/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package papeleria;
import java.sql.*;
import javax.swing.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julia
 */
public class VerProductos extends CenteredFrame {

    /**
     * Creates new form VerProductos
     */
    public void generarTable() {
        try {
            String url = "jdbc:postgresql://localhost:5432/Papeleria";
            String user = "postgres";
            String password = "9656";
            Connection con = DriverManager.getConnection(url, user, password);

            // Cambiar el esquema activo
            Statement stmt = con.createStatement();
            stmt.execute("SET search_path TO ciber_action");

            // Consulta SQL para obtener todos los empleados
            String sql = "SELECT * FROM producto";
            ResultSet rs = stmt.executeQuery(sql);

            // Obtener los metadatos de las columnas
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Crear un Vector para los nombres de las columnas
            Vector<String> columnNames = new Vector<>();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(metaData.getColumnName(i));
            }

            // Crear un Vector para las filas de la tabla
            Vector<Vector<Object>> data = new Vector<>();
            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                for (int i = 1; i <= columnCount; i++) {
                    row.add(rs.getObject(i));
                }
                data.add(row);
            }

            // Crear el modelo de la tabla y asignarlo al JTable
            DefaultTableModel model = new DefaultTableModel(data, columnNames);
            ProductosTable.setModel(model);

            // Cerrar la conexión
            stmt.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
        }
    }

    public VerProductos() {
        initComponents();
        generarTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductosTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Regresarbutt = new javax.swing.JButton();
        actualizarProd = new javax.swing.JButton();
        borrarProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VerInv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ProductosTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 375, 235));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        Regresarbutt.setBackground(new java.awt.Color(0, 102, 255));
        Regresarbutt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Regresarbutt.setText("Regresar");
        Regresarbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbuttActionPerformed(evt);
            }
        });

        actualizarProd.setBackground(new java.awt.Color(0, 102, 255));
        actualizarProd.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        actualizarProd.setForeground(new java.awt.Color(255, 255, 255));
        actualizarProd.setText("Actualizar");
        actualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarProdActionPerformed(evt);
            }
        });

        borrarProd.setBackground(new java.awt.Color(0, 102, 255));
        borrarProd.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        borrarProd.setForeground(new java.awt.Color(255, 255, 255));
        borrarProd.setText("Borrar");
        borrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarProdActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ppa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(actualizarProd, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(borrarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresarbutt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Regresarbutt)
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(actualizarProd)
                .addGap(35, 35, 35)
                .addComponent(borrarProd)
                .addGap(73, 73, 73))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 340));

        VerInv.setBackground(new java.awt.Color(0, 102, 255));
        VerInv.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        VerInv.setForeground(new java.awt.Color(255, 255, 255));
        VerInv.setText("Ver inventario");
        VerInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInvActionPerformed(evt);
            }
        });
        jPanel1.add(VerInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbuttActionPerformed
        agregarProductos agP = new agregarProductos();
        agP.setVisible(true); // Mostrar el frame de MenuGerente
        dispose(); // Cerrar el frame actual
    }//GEN-LAST:event_RegresarbuttActionPerformed

    private void actualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProdActionPerformed
        // Verificar si se ha seleccionado una fila
        int selectedRow = ProductosTable.getSelectedRow(); // Asegúrate de que ProdTable es el nombre correcto de tu tabla de productos
        if (selectedRow != -1) {
            // Convertir los valores obtenidos de la tabla a String de forma segura
            int id = (int) ProductosTable.getValueAt(selectedRow, 0);
            String nombre = ProductosTable.getValueAt(selectedRow, 1).toString();
            String descripcion = ProductosTable.getValueAt(selectedRow, 2).toString();
            String categoria = ProductosTable.getValueAt(selectedRow, 3).toString();
            String precio = ProductosTable.getValueAt(selectedRow, 4).toString(); // Asegúrate de que el precio se maneje correctamente

            // Abre el frame para actualizar producto
            new ActualizarProducto(id, nombre, descripcion, categoria, precio).setVisible(true);
            this.dispose(); // Cierra la ventana actual si es necesario
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.");
        }
    }//GEN-LAST:event_actualizarProdActionPerformed

    private void VerInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInvActionPerformed
        AgregarAlInventario agI = new AgregarAlInventario();
        agI.setVisible(true); // Mostrar el frame de MenuGerente
        dispose(); // Cerrar el frame actual
    }//GEN-LAST:event_VerInvActionPerformed

    private void borrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarProdActionPerformed
        try {
            // Verificar si se ha seleccionado una fila
            int selectedRow = ProductosTable.getSelectedRow(); // Asegúrate de que ProdTable es el nombre correcto de tu tabla de productos
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto en la tabla.");
                return;
            }

            // Obtener el ID del producto seleccionado
            int id = (int) ProductosTable.getValueAt(selectedRow, 0); // Suponiendo que el ID está en la primera columna

            // Mensaje de confirmación
            int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea borrar el producto?", "Confirmar Borrado", JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) {
                return; // Si el usuario selecciona "No", salir del método
            }

            String url = "jdbc:postgresql://localhost:5432/Papeleria";
            String user = "postgres";
            String password = "9656";
            Connection con = DriverManager.getConnection(url, user, password);

            // Cambiar el esquema activo
            Statement stmt = con.createStatement();
            stmt.execute("SET search_path TO ciber_action");

            // Consulta SQL para borrar un producto por su ID
            String sql = "DELETE FROM Producto WHERE Id_prod = ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setInt(1, id);

            // Ejecutar la consulta
            int rowsDeleted = pstmt.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente.");
                generarTable(); // Actualiza la tabla después de borrar
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un producto con ese ID.");
            }

            pstmt.close();
            stmt.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el producto: " + e.getMessage());
        }
    }//GEN-LAST:event_borrarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductosTable;
    private javax.swing.JButton Regresarbutt;
    private javax.swing.JButton VerInv;
    private javax.swing.JButton actualizarProd;
    private javax.swing.JButton borrarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
